package events

type EventType string

const (
	READY           EventType = "READY"
	RESUMED         EventType = "RESUMED"
	RECONNECT       EventType = "RECONNECT"
	INVALID_SESSION EventType = "INVALID_SESSION"

	APPLICATION_COMMAND_PERMISSIONS_UPDATE EventType = "APPLICATION_COMMAND_PERMISSIONS_UPDATE"

	AUTO_MODERATION_RULE_CREATE      EventType = "AUTO_MODERATION_RULE_CREATE"
	AUTO_MODERATION_RULE_UPDATE      EventType = "AUTO_MODERATION_RULE_UPDATE"
	AUTO_MODERATION_RULE_DELETE      EventType = "AUTO_MODERATION_RULE_DELETE"
	AUTO_MODERATION_ACTION_EXECUTION EventType = "AUTO_MODERATION_ACTION_EXECUTION"

	CHANNEL_CREATE      EventType = "CHANNEL_CREATE"
	CHANNEL_UPDATE      EventType = "CHANNEL_UPDATE"
	CHANNEL_DELETE      EventType = "CHANNEL_DELETE"
	CHANNEL_PINS_UPDATE EventType = "CHANNEL_PINS_UPDATE"

	THREAD_CREATE         EventType = "THREAD_CREATE"
	THREAD_UPDATE         EventType = "THREAD_UPDATE"
	THREAD_DELETE         EventType = "THREAD_DELETE"
	THREAD_LIST_SYNC      EventType = "THREAD_LIST_SYNC"
	THREAD_MEMBER_UPDATE  EventType = "THREAD_MEMBER_UPDATE"
	THREAD_MEMBERS_UPDATE EventType = "THREAD_MEMBERS_UPDATE"

	ENTITLEMENT_CREATE EventType = "ENTITLEMENT_CREATE"
	ENTITLEMENT_UPDATE EventType = "ENTITLEMENT_UPDATE"
	ENTITLEMENT_DELETE EventType = "ENTITLEMENT_DELETE"

	GUILD_CREATE                      EventType = "GUILD_CREATE"
	GUILD_UPDATE                      EventType = "GUILD_UPDATE"
	GUILD_DELETE                      EventType = "GUILD_DELETE"
	GUILD_AUDIT_LOG_ENTRY_CREATE      EventType = "GUILD_AUDIT_LOG_ENTRY_CREATE"
	GUILD_BAN_ADD                     EventType = "GUILD_BAN_ADD"
	GUILD_BAN_REMOVE                  EventType = "GUILD_BAN_REMOVE"
	GUILD_EMOJIS_UPDATE               EventType = "GUILD_EMOJIS_UPDATE"
	GUILD_STICKERS_UPDATE             EventType = "GUILD_STICKERS_UPDATE"
	GUILD_INTEGRATIONS_UPDATE         EventType = "GUILD_INTEGRATIONS_UPDATE"
	GUILD_MEMBER_ADD                  EventType = "GUILD_MEMBER_ADD"
	GUILD_MEMBER_REMOVE               EventType = "GUILD_MEMBER_REMOVE"
	GUILD_MEMBER_UPDATE               EventType = "GUILD_MEMBER_UPDATE"
	GUILD_MEMBERS_CHUNK               EventType = "GUILD_MEMBERS_CHUNK"
	GUILD_ROLE_CREATE                 EventType = "GUILD_ROLE_CREATE"
	GUILD_ROLE_UPDATE                 EventType = "GUILD_ROLE_UPDATE"
	GUILD_ROLE_DELETE                 EventType = "GUILD_ROLE_DELETE"
	GUILD_SCHEDULED_EVENT_CREATE      EventType = "GUILD_SCHEDULED_EVENT_CREATE"
	GUILD_SCHEDULED_EVENT_UPDATE      EventType = "GUILD_SCHEDULED_EVENT_UPDATE"
	GUILD_SCHEDULED_EVENT_DELETE      EventType = "GUILD_SCHEDULED_EVENT_DELETE"
	GUILD_SCHEDULED_EVENT_USER_ADD    EventType = "GUILD_SCHEDULED_EVENT_USER_ADD"
	GUILD_SCHEDULED_EVENT_USER_REMOVE EventType = "GUILD_SCHEDULED_EVENT_USER_REMOVE"
	GUILD_SOUNDBOARD_SOUND_CREATE     EventType = "GUILD_SOUNDBOARD_SOUND_CREATE"
	GUILD_SOUNDBOARD_SOUND_UPDATE     EventType = "GUILD_SOUNDBOARD_SOUND_UPDATE"
	GUILD_SOUNDBOARD_SOUND_DELETE     EventType = "GUILD_SOUNDBOARD_SOUND_DELETE"
	GUILD_SOUNDBOARD_SOUNDS_UPDATE    EventType = "GUILD_SOUNDBOARD_SOUNDS_UPDATE"

	SOUNDBOARD_SOUNDS EventType = "SOUNDBOARD_SOUNDS"

	INTEGRATION_CREATE EventType = "INTEGRATION_CREATE"
	INTEGRATION_UPDATE EventType = "INTEGRATION_UPDATE"
	INTEGRATION_DELETE EventType = "INTEGRATION_DELETE"

	INTERACTION_CREATE EventType = "INTERACTION_CREATE"

	INVITE_CREATE EventType = "INVITE_CREATE"
	INVITE_DELETE EventType = "INVITE_DELETE"

	MESSAGE_CREATE                EventType = "MESSAGE_CREATE"
	MESSAGE_UPDATE                EventType = "MESSAGE_UPDATE"
	MESSAGE_DELETE                EventType = "MESSAGE_DELETE"
	MESSAGE_DELETE_BULK           EventType = "MESSAGE_DELETE_BULK"
	MESSAGE_REACTION_ADD          EventType = "MESSAGE_REACTION_ADD"
	MESSAGE_REACTION_REMOVE       EventType = "MESSAGE_REACTION_REMOVE"
	MESSAGE_REACTION_REMOVE_ALL   EventType = "MESSAGE_REACTION_REMOVE_ALL"
	MESSAGE_REACTION_REMOVE_EMOJI EventType = "MESSAGE_REACTION_REMOVE_EMOJI"
	MESSAGE_POLL_VOTE_ADD         EventType = "MESSAGE_POLL_VOTE_ADD"
	MESSAGE_POLL_VOTE_REMOVE      EventType = "MESSAGE_POLL_VOTE_REMOVE"

	PRESENCE_UPDATE EventType = "PRESENCE_UPDATE"

	STAGE_INSTANCE_CREATE EventType = "STAGE_INSTANCE_CREATE"
	STAGE_INSTANCE_UPDATE EventType = "STAGE_INSTANCE_UPDATE"
	STAGE_INSTANCE_DELETE EventType = "STAGE_INSTANCE_DELETE"

	SUBSCRIPTION_CREATE EventType = "SUBSCRIPTION_CREATE"
	SUBSCRIPTION_UPDATE EventType = "SUBSCRIPTION_UPDATE"
	SUBSCRIPTION_DELETE EventType = "SUBSCRIPTION_DELETE"

	TYPING_START EventType = "TYPING_START"

	USER_UPDATE EventType = "USER_UPDATE"

	VOICE_CHANNEL_EFFECT_SEND EventType = "VOICE_CHANNEL_EFFECT_SEND"
	VOICE_STATE_UPDATE        EventType = "VOICE_STATE_UPDATE"
	VOICE_SERVER_UPDATE       EventType = "VOICE_SERVER_UPDATE"

	WEBHOOKS_UPDATE EventType = "WEBHOOKS_UPDATE"
)
